"""
Logging configuration for DLBot application.
Handles log file setup with daily rotation and custom formatting.
"""

import sys
import logging
from logging.handlers import TimedRotatingFileHandler
from pathlib import Path
from datetime import datetime
import io


def setup_logging() -> logging.Logger:
    """
    Configure logging with daily rotation using MMDD format.
    
    Returns:
        The configured root logger.
    """
    # Create logs directory
    log_dir = Path("logs")
    log_dir.mkdir(exist_ok=True)
    
    # Get current date in MMDD format
    current_date = datetime.now().strftime("%m%d")
    log_file = log_dir / f"dlbot_{current_date}.log"
    
    # Create TimedRotatingFileHandler for daily rotation at midnight
    file_handler = TimedRotatingFileHandler(
        str(log_file),
        when="midnight",
        interval=1,
        backupCount=30,
        encoding='utf-8'
    )
    
    # Set custom namer function to use MMDD format for rotated files
    file_handler.namer = _log_namer
    
    # Create console handler for stdout output
    console_handler = logging.StreamHandler(sys.stdout)
    
    # Configure console encoding for Windows
    _configure_console_encoding()
    
    # Create formatter
    formatter = logging.Formatter(
        "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    )
    file_handler.setFormatter(formatter)
    console_handler.setFormatter(formatter)
    
    # Configure root logger
    root_logger = logging.getLogger()
    root_logger.setLevel(logging.INFO)
    root_logger.addHandler(file_handler)
    root_logger.addHandler(console_handler)
    
    return root_logger


def _log_namer(default_name: str) -> str:
    """
    Custom namer function for rotated log files using MMDD format.
    
    Converts default TimedRotatingFileHandler names to use MMDD format.
    Example: "logs/dlbot_1120.log.2025-11-20" -> "logs/dlbot_1120.log"
    
    Args:
        default_name: The default name generated by TimedRotatingFileHandler.
        
    Returns:
        The formatted log file name with MMDD format.
    """
    log_dir = Path("logs")
    
    try:
        # Parse the date from the default name
        # Format: "logs/dlbot_MMDD.log.YYYY-MM-DD"
        parts = default_name.split('.')
        if len(parts) >= 3:
            date_str = parts[-1]  # "YYYY-MM-DD"
            # Convert to MMDD format
            date_obj = datetime.strptime(date_str, "%Y-%m-%d")
            mmdd = date_obj.strftime("%m%d")
            return str(log_dir / f"dlbot_{mmdd}.log")
    except (ValueError, IndexError):
        pass
    
    return default_name


def _configure_console_encoding() -> None:
    """
    Configure console encoding for Windows systems.
    Sets stdout to UTF-8 encoding to support special characters.
    """
    if sys.platform == 'win32' and sys.stdout is not None:
        try:
            sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
        except (AttributeError, ValueError):
            # If stdout is None or doesn't have buffer (e.g., running as EXE without console)
            pass
